function y = diffFilter(x)
%DIFFFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.4 and the DSP System Toolbox 8.7.
% Generated on: 19-Jan-2017 13:09:40

persistent Hd;

if isempty(Hd)
    
    Fpass = 0.45;  % Passband Frequency
    Fstop = 0.55;  % Stopband Frequency
    Apass = 1;     % Passband Ripple (dB)
    Astop = 60;    % Stopband Attenuation (dB)
    
    h = fdesign.differentiator('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop);
    
    Hd = design(h, 'equiripple');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


